# Generated by Django 5.2.6 on 2025-12-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
        migrations.AddField(
            model_name='news',
            name='code',
            field=models.SlugField(blank=True, help_text='Автоматично генерирано от заглавието', max_length=80, null=True, unique=True, verbose_name='Код (URL)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='Съдържание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Публикувана на'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Снимка'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заглавие'),
        ),
        migrations.AlterField(
            model_name='news',
            name='youtube_id',
            field=models.CharField(blank=True, help_text='Символите от url адреса след https://www.youtube.com/watch?v=', max_length=50, null=True, verbose_name='YouTube идентификатор'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Надпис'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(upload_to='news_images/', verbose_name='Снимка'),
        ),
    ]
