# Generated by Django 5.2.6 on 2025-12-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_slug_news_code_alter_news_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='code',
            field=models.SlugField(help_text='Автоматично генерирано от заглавието', max_length=80, unique=True, verbose_name='Код (URL)'),
        ),
    ]
