# Generated by Django 5.2.6 on 2025-12-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='youtube_id',
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='Снимка, която се показва в списъка с новини и в началото на статията', null=True, upload_to='news_images/', verbose_name='Водеща снимка'),
        ),
    ]
