# Generated by Django 5.2.6 on 2025-12-20 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_news_youtube_id_alter_news_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsImage',
        ),
    ]
