# Generated by Django 5.2.6 on 2025-10-08 21:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': [
                '-uploaded_at'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документи'},
        ),
        migrations.AlterModelOptions(
            name='documentcategory',
            options={'ordering': [
                'name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='supercategory',
            options={'ordering': [
                'name'], 'verbose_name': 'Суперкатегория', 'verbose_name_plural': 'Суперкатегории'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='order',
        ),
        migrations.RemoveField(
            model_name='document',
            name='published',
        ),
        migrations.RemoveField(
            model_name='documentcategory',
            name='order',
        ),
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='core.documentcategory'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='supercategory',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='core.supercategory'),
        ),
        migrations.AlterField(
            model_name='supercategory',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
