# Generated by Django 5.2.6 on 2025-10-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_document_slug_alter_documentcategory_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['order', '-uploaded_at'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документи'},
        ),
        migrations.AlterModelOptions(
            name='documentcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='supercategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Суперкатегория', 'verbose_name_plural': 'Суперкатегории'},
        ),
        migrations.AddField(
            model_name='document',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supercategory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
