# Generated by Django 5.2.6 on 2025-10-10 14:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['order', '-uploaded_at', 'title'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документи'},
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
