# Generated by Django 5.2.6 on 2025-10-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_document_options_alter_document_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='documentcategory',
            name='slug',
        ),
    ]
