# Generated by Django 5.2.6 on 2025-10-10 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_document_slug_remove_documentcategory_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['category', 'order', '-uploaded_at', 'title'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документи'},
        ),
    ]
