# Generated by Django 5.2.6 on 2025-10-10 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_document_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['category__supercategory__order', 'category__order', 'order', '-uploaded_at'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документи'},
        ),
    ]
