# Generated by Django 5.2.6 on 2025-10-10 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_documentcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentcategory',
            options={'ordering': ['supercategory__order', 'order'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
