# Generated by Django 5.2.6 on 2025-10-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_documentcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
