# Generated by Django 5.2.6 on 2025-10-19 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_document_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcategory',
            name='original_supercategory',
            field=models.ForeignKey(blank=True, help_text='Оригиналната суперкатегория, от която е архивирана тази категория.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_categories', to='core.supercategory'),
        ),
    ]
