# Generated by Django 5.2.6 on 2025-10-19 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_documentcategory_original_supercategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentcategory',
            name='original_supercategory',
        ),
        migrations.AddField(
            model_name='document',
            name='original_supercategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_documents', to='core.supercategory'),
        ),
    ]
