# Generated by Django 5.2.6 on 2025-12-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_news_options_newsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
