# Generated by Django 5.2.6 on 2025-12-05 03:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_galleryalbum_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.PositiveIntegerField(help_text='Номер на броя: 1, 2, 3...')),
                ('title', models.CharField(blank=True, help_text='Опционално заглавие на броя', max_length=255)),
                ('pdf', models.FileField(help_text='PDF файл на броя', upload_to='newspaper/')),
                ('cover_image', models.ImageField(blank=True, help_text='Качи снимка за превю (ако няма — ще се използва стандартна)', null=True, upload_to='newspaper_covers/')),
                ('published_at', models.DateField(default=django.utils.timezone.now, help_text='Дата на публикуване')),
            ],
            options={
                'verbose_name': 'Брой на училищния вестник',
                'verbose_name_plural': 'Училищен вестник',
                'ordering': ['-published_at', '-issue_number'],
            },
        ),
    ]
