# Generated by Django 5.2.6 on 2025-12-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_supercategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supercategory',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
