# Generated by Django 5.2.6 on 2025-12-09 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_supercategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='category',
        ),
        migrations.RemoveField(
            model_name='document',
            name='original_supercategory',
        ),
        migrations.AlterUniqueTogether(
            name='documentcategory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='documentcategory',
            name='supercategory',
        ),
        migrations.RemoveField(
            model_name='galleryalbum',
            name='related_news',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='album',
        ),
        migrations.RemoveField(
            model_name='newsimage',
            name='news',
        ),
        migrations.DeleteModel(
            name='Newspaper',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='DocumentCategory',
        ),
        migrations.DeleteModel(
            name='SuperCategory',
        ),
        migrations.DeleteModel(
            name='GalleryAlbum',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='NewsImage',
        ),
    ]
