# Generated by Django 5.2.6 on 2025-12-19 17:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0004_alter_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заглавие')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='gallery_covers/', verbose_name='Корица')),
                ('code', models.SlugField(help_text='Автоматично генериран от заглавието', unique=True, verbose_name='Код (URL)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ред')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Създаден на')),
                ('related_news', models.ForeignKey(blank=True, help_text='По желание можеш да свържеш албума с новина.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.news', verbose_name='Свързана новина')),
            ],
            options={
                'verbose_name': 'Фото албум',
                'verbose_name_plural': 'Фото албуми',
                'ordering': ['order', '-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Снимка')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ред')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.galleryalbum', verbose_name='Албум')),
            ],
            options={
                'verbose_name': 'Снимка',
                'verbose_name_plural': 'Снимки',
                'ordering': ['order'],
            },
        ),
    ]
