# Generated by Django 5.2.6 on 2025-12-20 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(help_text='Постави линк към YouTube или Vimeo видео', verbose_name='Видео (YouTube / Vimeo)')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заглавие')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ред')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='gallery.galleryalbum', verbose_name='Албум')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видеа',
                'ordering': ['order', 'id'],
            },
        ),
    ]
