# Generated by Django 5.2.6 on 2025-12-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_galleryvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryvideo',
            name='video_url',
            field=models.URLField(help_text='Постави линк към YouTube видео', verbose_name='YouTube видео'),
        ),
    ]
