# Generated by Django 5.2.6 on 2025-12-20 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_galleryvideo_video_url'),
        ('news', '0004_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='news.news', verbose_name='Новина'),
        ),
        migrations.AddField(
            model_name='galleryvideo',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_videos', to='news.news', verbose_name='Новина'),
        ),
        migrations.AlterField(
            model_name='galleryvideo',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='gallery.galleryalbum', verbose_name='Албум'),
        ),
    ]
