# Generated by Django 5.2.6 on 2025-12-20 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_galleryimage_news_galleryvideo_news_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.galleryalbum', verbose_name='Албум'),
        ),
    ]
