# Generated by Django 5.2.6 on 2025-12-20 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_galleryimage_album'),
        ('news', '0006_delete_newsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryalbum',
            name='related_news',
            field=models.ForeignKey(blank=True, help_text='По желание можеш да свържеш албума с новина.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_albums', to='news.news', verbose_name='Свързана новина'),
        ),
    ]
