# Generated by Django 5.2.6 on 2026-01-12 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creativity', '0001_initial'),
        ('gallery', '0006_alter_galleryalbum_related_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='creative_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='creativity.creativework', verbose_name='Творба'),
        ),
    ]
