# Generated by Django 5.2.6 on 2025-12-11 22:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и час на публикуване'),
        ),
    ]
