# Generated by Django 5.2.6 on 2025-12-19 02:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'name')},
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.SlugField(help_text='Само латиница, напр. archive, budget, programs', unique=True, validators=[django.core.validators.RegexValidator(message='Използвай само малки латински букви, цифри и тире.', regex='^[a-z0-9-]+$')], verbose_name='Код (URL)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ред'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ред'),
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='code',
        ),
    ]
