# Generated by Django 5.2.6 on 2025-12-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_subcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.SlugField(help_text='Само латиница, напр. archive, budget, programs', unique=True, verbose_name='Код (URL)'),
        ),
    ]
