# Generated by Django 5.2.6 on 2025-12-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_category_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(help_text='Автоматично от името, може да се редактира', max_length=50, unique=True, verbose_name='Код (URL)'),
        ),
    ]
