# Generated by Django 5.2.6 on 2025-12-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_category_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(help_text='Автоматично генериран от името', max_length=50, unique=True, verbose_name='Код (URL)'),
        ),
    ]
