# Generated by Django 5.2.6 on 2025-12-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_category_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.SlugField(help_text='Автоматично генериран от името', unique=True, verbose_name='Код (URL)'),
        ),
    ]
