# Generated by Django 5.2.6 on 2026-01-12 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_document_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['subcategory__category__order', 'subcategory__category__name', 'subcategory__order', 'subcategory__name', '-uploaded_at', 'title'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документи'},
        ),
    ]
