# Generated by Django 5.2.6 on 2026-01-12 09:35

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заглавие')),
                ('author', models.CharField(blank=True, help_text='По желание (ученик, клас, псевдоним)', max_length=255, verbose_name='Автор')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Ако не избереш дата, ще се използва днешната', verbose_name='Дата на публикуване')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Съдържание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='creativity_images/', verbose_name='Водеща снимка')),
                ('code', models.SlugField(help_text='Автоматично генериран от заглавието', max_length=80, unique=True, verbose_name='Код (URL)')),
            ],
            options={
                'verbose_name': 'Творба',
                'verbose_name_plural': 'Творчество',
                'ordering': ['-published_at'],
            },
        ),
    ]
