# Generated by Django 5.2.6 on 2026-01-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creativity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativework',
            name='image',
            field=models.ImageField(blank=True, help_text='По желание', null=True, upload_to='creativity_images/', verbose_name='Водеща снимка'),
        ),
    ]
